version: 2.1

workflows:
  main:
    jobs:
      - hof_ci:
          context: SonarCloud

jobs:

  # Build and test hof, in that order!
  hof_ci:
    machine: true

    steps:
      - checkout

      # setup and dependencies fetch
      - run: |
          # fetch deps
          go mod vendor

          # install Cue
          # curl -LO https://github.com/cuelang/cue/releases/download/v0.2.0/cue_0.2.0_Linux_x86_64.tar.gz
          # tar -xf cue_0.2.0_Linux_x86_64.tar.gz
          # sudo mv cue /usr/local/bin/cue

      # This seems backwards, we ought to test, but...
      - run: |
          # build hof
          go build -o hof cmd/hof/main.go

      # Fetch cue deps
      - run: |
          ./hof mod vendor cue

      # Hof has a built in test command to facilitate running tests
      # en masse, regardless of the language, technology, or framework
      # you can also script all of the processes that go around a
      # complete testing setup with tasks like collectiong and reporting coverage statistics
      - run: |
          # run all tests
          ./hof test test.cue

          # TODO, temp hack until tests are actually running
          mkdir -p sonar-reports/go

      # Debug stip
      - run: |
          echo "------  root dir   ------"
          ls -lh .
          echo "------  sonar dir  ------"
          ls -lh sonar-reports
          echo "------  end debug  ------"

      # Build our custom image
      - run: |
          # build our own sonar container
          ./ci/sc/build.sh

      # Upload reports now that they have been generated and collected
      - run: |
          # run our own sonar containers
          ./ci/sc/run.sh

